language: r
os: osx
sudo: required
bioc_required: true
r_check_args: '--as-cran --no-examples'
r_github_packages:
  - jimhester/covr
  - hadley/dplyr
after_success:
  - Rscript -e 'library(covr);codecov()'
